"""" ===== Modern Vim: Minimal Configuration =====
set nocompatible
filetype plugin indent on

"""" ===== Modern Vim Tip 24: Making Undo Persist Between Sessions =====
set undofile
if !has('nvim')
  set undodir=~/.vim/undo
endif
augroup vimrc
  autocmd!
  autocmd BufWritePre /tmp/* setlocal noundofile
augroup END

"""" ===== Pratical Vim Tip 32: Tab-Complete Your Ex Commands =====
set wildmenu
set wildmode=full

"""" ===== Pratical Vim Tip 34: Recall Commands from History =====
set history=200

"""" ===== Pratical Vim Tip 39: Manage Hidden Files =====
set hidden

"""" ===== Pratical Vim Tip 42: Easy Expansion of the Active File Directory =====
cnoremap <expr> %%  getcmdtype() == ':' ? fnameescape(expand('%:h')).'/' : '%%'

"""" ===== Pratical Vim Tip 48: Distinguish Between Real Lines and Display Lines =====
set nowrap

"""" ===== Pratical Vim Tip 50: Don’t Throw Away the Reverse Character Search Command =====
let mapleader=","
noremap \ ,

"""" ===== Pratical Vim Tip 64: Interact with the System Clipboard =====
set autoindent

"""" ===== Pratical Vim Tip 73: Tune the Case Sensitivity of Search Patterns =====
set ignorecase
set smartcase

"""" ===== Pratical Vim Tip 81: Highlight Search Matches =====
set hlsearch
nnoremap <silent> <leader>l :<C-u>nohlsearch<CR>

"""" ===== Pratical Vim Tip 82: Preview the First Match Before Execution =====
set incsearch

"""" ===== Pratical Vim Tip 93: Fixing the & Command =====
nnoremap & :&&<CR>
xnoremap & :&&<CR>

"""" ===== Pratical Vim Appendix 1: Use four spaces for indentation =====
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

"""" ===== various =====
set number
set smarttab
set smartindent

"""" ===== yank to system clipboard =====
if executable('win32yank.exe')
  let s:clip = 'win32yank.exe -i --crlf'
elseif executable('wl-copy')
  let s:clip = 'wl-copy'
elseif executable('xclip')
  let s:clip = 'xclip -selection clipboard -in'
elseif executable('pbcopy')
  let s:clip = 'pbcopy'
endif
if exists('s:clip')
  augroup YankClipboard
    autocmd!
    autocmd TextYankPost * silent! call system(s:clip, join(v:event.regcontents, "\n"))
  augroup END
endif

"""" ===== syntax =====
syntax enable

if &t_Co == 256
  highlight LineNr     ctermfg=145    guifg=Gray
  highlight Search     ctermbg=227    guibg=Yellow
  highlight MatchParen ctermbg=227    guibg=Yellow
  highlight DiffAdd                   ctermfg=black cterm=bold guibg=green      guifg=black
  highlight DiffText   ctermbg=yellow ctermfg=red   cterm=bold guibg=yellow     guifg=red
  highlight DiffChange ctermbg=none   ctermfg=none  cterm=bold guibg=white      guifg=black
  highlight DiffDelete                                         guibg=lightblue  guifg=lightblue
endif
set background=light

"""" ===== Plugin: lightline.vim =====
function! GitConflictLines()
  let l:patterns = ['^<<<<<<< ']
  let l:conflict_lines = filter(range(1, line('$')), 'match(getline(v:val), join(l:patterns, "\\|")) != -1')
  return !empty(l:conflict_lines) ? '[ ' . join(l:conflict_lines, ' ') . ' ] conflicts' : ''
endfunction

let g:lightline = {
      \ 'colorscheme': 'ayu_light',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified', 'gitconflict' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ 'component_expand': {
      \   'gitconflict': 'GitConflictLines'
      \ },
      \ 'component_type': {
      \   'gitconflict': 'warning'
      \ }
      \ }
set laststatus=2
set noshowmode
set shortmess-=S

"""" ===== Plugin: arm-syntax-vim =====
au BufNewFile,BufRead *.s,*.S set filetype=arm " arm = armv6/7

"""" ===== Plugin: python-syntax =====
let g:python_highlight_all = 1

"""" ===== Plugin: fzf =====
nnoremap <leader>f :<C-u>FZF<CR>

"""" ===== Plugin: vim-grepper =====
nnoremap <leader>g :Grepper<cr>

let g:grepper       = {}
let g:grepper.tools = ['rg']

nmap <C-n> :cnext<CR>
nmap <C-p> :cprev<CR>

"""" ===== Plugin: tagbar =====
let g:tagbar_left = 1
let g:tagbar_width = max([25, winwidth(0) / 5])
let g:tagbar_sort = 0

set tags=./tags;,tags
set updatetime=100

nnoremap <silent> <leader>t :TagbarToggle<CR>

"""" ===== Modern Vim Tip 17: Seamlessly Navigating tmux Panes and Vim Windows =====
let  g:tmux_navigator_no_wrap = 1

"""" ===== Modern Vim Tip 6: Managing Plugins with minpac =====
function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  " File and syntax enhancements
  call minpac#add('andymass/vim-matchup')
  call minpac#add('justinmk/vim-syntax-extra')
  call minpac#add('ARM9/arm-syntax-vim')
  call minpac#add('bfrg/vim-c-cpp-modern')
  call minpac#add('vim-python/python-syntax')

  " Search tools and version control
  call minpac#add('junegunn/fzf')
  call minpac#add('mhinz/vim-grepper')
  call minpac#add('junegunn/gv.vim')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('christoomey/vim-conflicted')

  " Navigation and UI enhancements
  call minpac#add('preservim/tagbar')
  call minpac#add('itchyny/lightline.vim')
  call minpac#add('tpope/vim-vinegar')
  call minpac#add('christoomey/vim-tmux-navigator')

  " Editing utilities and shortcuts
  call minpac#add('bronson/vim-visual-star-search')
  call minpac#add('ConradIrwin/vim-bracketed-paste')
endfunction

command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()
command! PackUpdateQuit call PackInit() | call minpac#update('', {'do': 'qall'})
