export PATH="$HOME/.local/bin:$PATH"
export LANG="en_US.UTF-8"

if command -v vimx &>/dev/null; then
    export EDITOR="vimx"
    export VISUAL="vimx"
    alias vim="vimx"
else
    export EDITOR="vim"
    export VISUAL="vim"
fi

export HISTSIZE=10000
export SAVEHIST=10000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt NO_CLOBBER

command -v bat   &>/dev/null && export BAT_THEME="ansi"
command -v bat   &>/dev/null && alias cat="bat --plain"
command -v fzf   &>/dev/null && source <(fzf --zsh)
