#!/bin/bash

if [ "$#" -eq 2 ]; then
  LOCAL="$1"
  REMOTE="$2"
  "/c/Program Files/WinMerge/WinMergeU.exe" -u -e "$LOCAL" "$REMOTE"

elif [ "$#" -eq 3 ]; then
  LOCAL="$1"
  REMOTE="$2"
  MERGED="$3"
  "/c/Program Files/WinMerge/WinMergeU.exe" -u -e -dl "Local" -dr "Remote" "$LOCAL" "$REMOTE" "$MERGED"

else
  echo "Usage error: please provide 2 or 3 file paths"
  exit 1
fi
