#!/bin/bash

if [ "$#" -eq 0 ]; then
    ccal -p -b -u | convert -density 1200 - -resize 25% -gravity center -background "#008264" -extent 3840x2160 calendar.png
elif [ "$#" -eq 1 ]; then
    ccal -p -b -u ${1} | convert -density 1200 - -resize 25% -gravity center -background "#008264" -extent 3840x2160 calendar.png
elif [ "$#" -eq 2 ]; then
    ccal -p -b -u ${1} ${2} | convert -density 1200 - -resize 25% -gravity center -background "#008264" -extent 3840x2160 calendar.png
else
    echo "Usage error: up to two parameters [[<month>] <year>]"
    exit 1
fi
