#!/bin/bash

if command -v magick >/dev/null 2>&1; then
    IM_CMD="magick"
else
    IM_CMD="convert"
fi

ccal -p -b -u "$@" | $IM_CMD -density 1200 - -resize 25% -gravity center -background "#008264" -extent 3840x2160 calendar.png
