#!/bin/bash

if [ "$#" -eq 2 ]; then
    LOCAL="$1"
    REMOTE="$2"
    meld "$LOCAL" "$REMOTE"
elif [ "$#" -eq 4 ]; then
    LOCAL="$1"
    BASE="$2"
    REMOTE="$3"
    MERGED="$4"
    meld "$LOCAL" "$BASE" "$REMOTE" --output="$MERGED"
else
    echo "Usage error: please provide 2 or 4 file paths"
    exit 1
fi
