#!/bin/bash

to_win_path() {
  wslpath -w "$1"
}

if [ "$#" -eq 2 ]; then
  LOCAL=$(to_win_path "$1")
  REMOTE=$(to_win_path "$2")
  "/mnt/c/Program Files/WinMerge/WinMergeU.exe" -u -e "$LOCAL" "$REMOTE"

elif [ "$#" -eq 3 ]; then
  LOCAL=$(to_win_path "$1")
  REMOTE=$(to_win_path "$2")
  MERGED=$(to_win_path "$3")
  "/mnt/c/Program Files/WinMerge/WinMergeU.exe" -u -e -dl "Local" -dr "Remote" "$LOCAL" "$REMOTE" "$MERGED"

else
  echo "Usage error: please provide 2 or 3 file paths"
  exit 1
fi
