[window]
padding = { x = 10, y = 10 }

[mouse]
hide_when_typing = true

[font]
normal = { family = "Cascadia Mono", style = "Regular" }
size = 12.0

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.normal]
black   = "#000000"
red     = "#AA0000"
green   = "#00AA00"
yellow  = "#AA5500"
blue    = "#0000AA"
magenta = "#AA00AA"
cyan    = "#00AAAA"
white   = "#AAAAAA"

[colors.bright]
black   = "#000000"
red     = "#AA0000"
green   = "#00AA00"
yellow  = "#AA5500"
blue    = "#0000AA"
magenta = "#AA00AA"
cyan    = "#00AAAA"
white   = "#AAAAAA"
